name: ROOT
dependencies:
  '@types/prettier': ^2.7.3
  tslib: ^2.6.0
pnpm:
  overrides:
    '@build-script/heft-esbuild-plugin': >-
      /data/DevelopmentRoot/github.com/gongt/baobao/@build-script/heft-esbuild-plugin
